"project_id" : CROWDIN_PROJECT_ID
"api_token" : CROWDIN_PERSONAL_TOKEN
"base_path" : "."
"base_url" : "https://api.crowdin.com"
"preserve_hierarchy": true
files: [
  {
     source: /src/i18n/zh-CN/*.json,
    'translation': '/src/i18n/%locale%/%original_file_name%',
  },
]
